const fs = require('fs');
const fpath = 'src/dashboardProvider.ts';
let content = fs.readFileSync(fpath, 'utf8');

const oldFunc = `function setBadge(id, count, total, err) {\\n        const b = document.getElementById(id);\\n        if (!b) return;\\n        const baseStyle = 'font-size:9px; padding:2px 6px; border-radius:4px; font-weight:bold; white-space:nowrap; display:flex; align-items:center; gap:4px;';\\n        if (err) {\\n            b.innerHTML = '<span style=\\\\"font-size:8px;\\\\">▲</span> LIMIT';\\n            b.style = baseStyle + ' background:rgba(255,42,42,0.1); color:var(--red); border:1px solid var(--red);';\\n        } else if (count === 0) {\\n            b.innerHTML = '<span style=\\\\"font-size:8px;\\\\">○</span> N/A';\\n            b.style = baseStyle + ' background:rgba(255,255,255,0.05); color:var(--text-muted); border:1px solid var(--text-muted);';\\n        } else {\\n            const avg = total / count;\\n            if (avg > 20) {\\n                b.innerHTML = '<span style=\\\\"font-size:8px;\\\\">●</span> LIVE';\\n                b.style = baseStyle + ' background:rgba(0,255,102,0.1); color:var(--green); border:1px solid var(--green);';\\n            } else {\\n                b.innerHTML = '<span style=\\\\"font-size:8px;\\\\">●</span> DEGRADED';\\n                b.style = baseStyle + ' background:rgba(212,168,67,0.1); color:var(--gold); border:1px solid var(--gold);';\\n            }\\n        }\\n    }`;

// Define the exact new string.
const newFunc = `function setBadge(id, count, total, err) {\\n        const b = document.getElementById(id);\\n        if (!b) return;\\n        const baseStyle = 'font-size:9px; padding:2px 6px; border-radius:4px; font-weight:bold; white-space:nowrap; display:inline-flex; align-items:center; gap:4px;';\\n        if (err) {\\n            b.innerHTML = '<span style=\\\\"font-size:8px;\\\\">▲</span> LIMIT';\\n            b.style = baseStyle + ' background:rgba(255,42,42,0.1); color:var(--red); border:1px solid var(--red);';\\n            return;\\n        }\\n        if (st === \\'LIKELY_OUTAGE\\') {\\n            b.innerHTML = '<span style=\\\\"font-size:8px;\\\\">▲</span> OUTAGE';\\n            b.style = baseStyle + ' background:rgba(255,42,42,0.1); color:var(--red); border:1px solid var(--red);';\\n            return;\\n        }\\n        if (st === \\'POSSIBLE_OUTAGE\\') {\\n            b.innerHTML = '<span style=\\\\"font-size:8px;\\\\">◆</span> UNSTABLE';\\n            b.style = baseStyle + ' background:rgba(212,168,67,0.1); color:var(--gold); border:1px solid var(--gold);';\\n            return;\\n        }\\n        if (st === \\'MAINTENANCE\\') {\\n            b.innerHTML = '<span style=\\\\"font-size:8px;\\\\">⚙</span> MAINT';\\n            b.style = baseStyle + ' background:rgba(124,109,216,0.1); color:#7c6dd8; border:1px solid #7c6dd8;';\\n            return;\\n        }\\n        if (count === 0) {\\n            b.innerHTML = '<span style=\\\\"font-size:8px;\\\\">○</span> N/A';\\n            b.style = baseStyle + ' background:rgba(255,255,255,0.05); color:var(--text-muted); border:1px solid var(--text-muted);';\\n            return;\\n        }\\n        const avg = total / count;\\n        if (avg > 20) {\\n            b.innerHTML = '<span style=\\\\"font-size:8px;\\\\">●</span> LIVE';\\n            b.style = baseStyle + ' background:rgba(0,255,102,0.1); color:var(--green); border:1px solid var(--green);';\\n        } else if (avg > 0) {\\n            b.innerHTML = '<span style=\\\\"font-size:8px;\\\\">●</span> DEGRADED';\\n            b.style = baseStyle + ' background:rgba(212,168,67,0.1); color:var(--gold); border:1px solid var(--gold);';\\n        } else {\\n            b.innerHTML = '<span style=\\\\"font-size:8px;\\\\">▲</span> EXHAUSTED';\\n            b.style = baseStyle + ' background:rgba(255,42,42,0.1); color:var(--red); border:1px solid var(--red);';\\n        }\\n    }`;

// Clean strings of escaped quotes to bypass mismatch issues
const searchOld = oldFunc.replace(/\\\\"/g, '\\"');
const replaceNew = newFunc.replace(/\\\\"/g, '\\"').replace(/\\'/g, "'");

if (content.includes(searchOld)) {
    content = content.replace(searchOld, replaceNew);
    fs.writeFileSync(fpath, content, 'utf8');
    console.log('SUCCESS: replaced!');
} else {
    console.log('ERROR: Could not find exact search string.');
}
